package com.wm.notification.enums;

public enum Events {

    JOB_APPLICATION_REQUEST, CUSTOM_SERVICE_REQUEST, CUSTOM_SERVICE_REQUEST_STATUS, JOB_INVITATION_REQUEST, JOB_INVITATION_REQUEST_STATUS,

    WARRANT_TRANSFER, OFFER_REQUEST, OFFER_REQUEST_STATUS, SERVICE_ORDER_PAYMENT, PAYMENT_RELEASED, GUARANTOR_REQUEST, GUARANTOR_REQUEST_STATUS,

    SERVICE_ORDER_APPROVAL_REQUEST, SERVICE_ORDER_APPROVAL, PCR_TRANSFER, JOB_ASSIGNED
}